CREATE TABLE users (
  userID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  age INT(11) NOT NULL,
  dob DATE NOT NULL,
  mobile VARCHAR(20) NOT NULL
);
